/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DonationEntry {
    donationType: DonationType;
    submittedBy: string;
    notes: string;
    timestamp: Time;
}
export type DonorId = number;
export type Time = bigint;
export interface Donor {
    initialDonationType: DonationType;
    mapLink?: string;
    name: string;
    logNumber: DonorId;
    addressNumber: string;
    address: string;
    notes: string;
    addedDate: Time;
    place: string;
    donations: Array<DonationEntry>;
}
export interface SubAccount {
    username: string;
    role: Role;
    passwordHash: string;
}
export interface ImportResult {
    errors: Array<[bigint, string]>;
    totalRows: bigint;
    importedCount: bigint;
}
export type DonationType = {
    __kind__: "money";
    money: number;
} | {
    __kind__: "groceries";
    groceries: Array<GroceryItem>;
};
export interface GroceryItem {
    name: string;
    quantity?: string;
}
export interface UserProfile {
    name: string;
}
export enum Role {
    admin = "admin",
    user = "user"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDonationRecord(donorId: DonorId, donationEntry: DonationEntry): Promise<void>;
    addGroceryItem(item: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateSubAccount(username: string, passwordHash: string): Promise<Role | null>;
    bulkImport(_csvData: string): Promise<ImportResult>;
    createDonor(name: string, address: string, addressNumber: string, place: string, donationType: DonationType, notes: string, mapLink: string | null): Promise<DonorId>;
    createSubAccount(username: string, passwordHash: string, role: Role): Promise<void>;
    deleteDonor(logNumber: DonorId): Promise<void>;
    deleteGroceryItem(item: string): Promise<void>;
    deleteSubAccount(username: string): Promise<void>;
    editDonor(logNumber: DonorId, name: string, address: string, addressNumber: string, place: string, donationType: DonationType, notes: string, mapLink: string | null): Promise<void>;
    getAllDonors(): Promise<Array<Donor>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationsByDateRange(donorId: DonorId, startDate: Time, endDate: Time): Promise<Array<DonationEntry>>;
    getDonationsForDonor(donorId: DonorId): Promise<Array<DonationEntry>>;
    getDonor(logNumber: DonorId): Promise<Donor | null>;
    getDonorsByPlace(place: string): Promise<Array<Donor>>;
    getGroceryItems(): Promise<Array<string>>;
    getRoleTypes(): Promise<Array<Role>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listSubAccounts(): Promise<Array<SubAccount>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DonationEntry as _DonationEntry, DonationType as _DonationType, Donor as _Donor, DonorId as _DonorId, GroceryItem as _GroceryItem, Role as _Role, SubAccount as _SubAccount, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDonationRecord(arg0: DonorId, arg1: DonationEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonationRecord(arg0, to_candid_DonationEntry_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonationRecord(arg0, to_candid_DonationEntry_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addGroceryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroceryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroceryItem(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateSubAccount(arg0: string, arg1: string): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateSubAccount(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateSubAccount(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async bulkImport(arg0: string): Promise<ImportResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImport(arg0);
            return result;
        }
    }
    async createDonor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: DonationType, arg5: string, arg6: string | null): Promise<DonorId> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonor(arg0, arg1, arg2, arg3, to_candid_DonationType_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonor(arg0, arg1, arg2, arg3, to_candid_DonationType_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createSubAccount(arg0: string, arg1: string, arg2: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubAccount(arg0, arg1, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubAccount(arg0, arg1, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteDonor(arg0: DonorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonor(arg0);
            return result;
        }
    }
    async deleteGroceryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroceryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroceryItem(arg0);
            return result;
        }
    }
    async deleteSubAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubAccount(arg0);
            return result;
        }
    }
    async editDonor(arg0: DonorId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: DonationType, arg6: string, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editDonor(arg0, arg1, arg2, arg3, arg4, to_candid_DonationType_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDonor(arg0, arg1, arg2, arg3, arg4, to_candid_DonationType_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async getAllDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonors();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonors();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationsByDateRange(arg0: DonorId, arg1: Time, arg2: Time): Promise<Array<DonationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByDateRange(arg0, arg1, arg2);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByDateRange(arg0, arg1, arg2);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationsForDonor(arg0: DonorId): Promise<Array<DonationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsForDonor(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsForDonor(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonor(arg0: DonorId): Promise<Donor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonor(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonor(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorsByPlace(arg0: string): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorsByPlace(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorsByPlace(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroceryItems(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroceryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroceryItems();
            return result;
        }
    }
    async getRoleTypes(): Promise<Array<Role>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoleTypes();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoleTypes();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSubAccounts(): Promise<Array<SubAccount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubAccounts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubAccounts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_DonationEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationEntry): DonationEntry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DonationType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonationType): DonationType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_GroceryItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroceryItem): GroceryItem {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SubAccount_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubAccount): SubAccount {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donor]): Donor | null {
    return value.length === 0 ? null : from_candid_Donor_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initialDonationType: _DonationType;
    mapLink: [] | [string];
    name: string;
    logNumber: _DonorId;
    addressNumber: string;
    address: string;
    notes: string;
    addedDate: _Time;
    place: string;
    donations: Array<_DonationEntry>;
}): {
    initialDonationType: DonationType;
    mapLink?: string;
    name: string;
    logNumber: DonorId;
    addressNumber: string;
    address: string;
    notes: string;
    addedDate: Time;
    place: string;
    donations: Array<DonationEntry>;
} {
    return {
        initialDonationType: from_candid_DonationType_n19(_uploadFile, _downloadFile, value.initialDonationType),
        mapLink: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.mapLink)),
        name: value.name,
        logNumber: value.logNumber,
        addressNumber: value.addressNumber,
        address: value.address,
        notes: value.notes,
        addedDate: value.addedDate,
        place: value.place,
        donations: from_candid_vec_n25(_uploadFile, _downloadFile, value.donations)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quantity: [] | [string];
}): {
    name: string;
    quantity?: string;
} {
    return {
        name: value.name,
        quantity: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.quantity))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationType: _DonationType;
    submittedBy: string;
    notes: string;
    timestamp: _Time;
}): {
    donationType: DonationType;
    submittedBy: string;
    notes: string;
    timestamp: Time;
} {
    return {
        donationType: from_candid_DonationType_n19(_uploadFile, _downloadFile, value.donationType),
        submittedBy: value.submittedBy,
        notes: value.notes,
        timestamp: value.timestamp
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: _Role;
    passwordHash: string;
}): {
    username: string;
    role: Role;
    passwordHash: string;
} {
    return {
        username: value.username,
        role: from_candid_Role_n11(_uploadFile, _downloadFile, value.role),
        passwordHash: value.passwordHash
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: number;
} | {
    groceries: Array<_GroceryItem>;
}): {
    __kind__: "money";
    money: number;
} | {
    __kind__: "groceries";
    groceries: Array<GroceryItem>;
} {
    return "money" in value ? {
        __kind__: "money",
        money: value.money
    } : "groceries" in value ? {
        __kind__: "groceries",
        groceries: from_candid_vec_n21(_uploadFile, _downloadFile, value.groceries)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroceryItem>): Array<GroceryItem> {
    return value.map((x)=>from_candid_GroceryItem_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonationEntry>): Array<DonationEntry> {
    return value.map((x)=>from_candid_DonationEntry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Role>): Array<Role> {
    return value.map((x)=>from_candid_Role_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubAccount>): Array<SubAccount> {
    return value.map((x)=>from_candid_SubAccount_n34(_uploadFile, _downloadFile, x));
}
function to_candid_DonationEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationEntry): _DonationEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DonationType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonationType): _DonationType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GroceryItem_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GroceryItem): _GroceryItem {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    donationType: DonationType;
    submittedBy: string;
    notes: string;
    timestamp: Time;
}): {
    donationType: _DonationType;
    submittedBy: string;
    notes: string;
    timestamp: _Time;
} {
    return {
        donationType: to_candid_DonationType_n3(_uploadFile, _downloadFile, value.donationType),
        submittedBy: value.submittedBy,
        notes: value.notes,
        timestamp: value.timestamp
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quantity?: string;
}): {
    name: string;
    quantity: [] | [string];
} {
    return {
        name: value.name,
        quantity: value.quantity ? candid_some(value.quantity) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "money";
    money: number;
} | {
    __kind__: "groceries";
    groceries: Array<GroceryItem>;
}): {
    money: number;
} | {
    groceries: Array<_GroceryItem>;
} {
    return value.__kind__ === "money" ? {
        money: value.money
    } : value.__kind__ === "groceries" ? {
        groceries: to_candid_vec_n5(_uploadFile, _downloadFile, value.groceries)
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GroceryItem>): Array<_GroceryItem> {
    return value.map((x)=>to_candid_GroceryItem_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
