/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DonorId = IDL.Nat32;
export const GroceryItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Opt(IDL.Text),
});
export const DonationType = IDL.Variant({
  'money' : IDL.Nat32,
  'groceries' : IDL.Vec(GroceryItem),
});
export const Time = IDL.Int;
export const DonationEntry = IDL.Record({
  'donationType' : DonationType,
  'submittedBy' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const ImportResult = IDL.Record({
  'errors' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'totalRows' : IDL.Nat,
  'importedCount' : IDL.Nat,
});
export const Donor = IDL.Record({
  'initialDonationType' : DonationType,
  'mapLink' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'logNumber' : DonorId,
  'addressNumber' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'addedDate' : Time,
  'place' : IDL.Text,
  'donations' : IDL.Vec(DonationEntry),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SubAccount = IDL.Record({
  'username' : IDL.Text,
  'role' : Role,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDonationRecord' : IDL.Func([DonorId, DonationEntry], [], []),
  'addGroceryItem' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateSubAccount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Role)],
      ['query'],
    ),
  'bulkImport' : IDL.Func([IDL.Text], [ImportResult], []),
  'createDonor' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        DonationType,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [DonorId],
      [],
    ),
  'createSubAccount' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
  'deleteDonor' : IDL.Func([DonorId], [], []),
  'deleteGroceryItem' : IDL.Func([IDL.Text], [], []),
  'deleteSubAccount' : IDL.Func([IDL.Text], [], []),
  'editDonor' : IDL.Func(
      [
        DonorId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        DonationType,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationsByDateRange' : IDL.Func(
      [DonorId, Time, Time],
      [IDL.Vec(DonationEntry)],
      ['query'],
    ),
  'getDonationsForDonor' : IDL.Func(
      [DonorId],
      [IDL.Vec(DonationEntry)],
      ['query'],
    ),
  'getDonor' : IDL.Func([DonorId], [IDL.Opt(Donor)], ['query']),
  'getDonorsByPlace' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
  'getGroceryItems' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRoleTypes' : IDL.Func([], [IDL.Vec(Role)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubAccounts' : IDL.Func([], [IDL.Vec(SubAccount)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DonorId = IDL.Nat32;
  const GroceryItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Opt(IDL.Text),
  });
  const DonationType = IDL.Variant({
    'money' : IDL.Nat32,
    'groceries' : IDL.Vec(GroceryItem),
  });
  const Time = IDL.Int;
  const DonationEntry = IDL.Record({
    'donationType' : DonationType,
    'submittedBy' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const ImportResult = IDL.Record({
    'errors' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'totalRows' : IDL.Nat,
    'importedCount' : IDL.Nat,
  });
  const Donor = IDL.Record({
    'initialDonationType' : DonationType,
    'mapLink' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'logNumber' : DonorId,
    'addressNumber' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'addedDate' : Time,
    'place' : IDL.Text,
    'donations' : IDL.Vec(DonationEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SubAccount = IDL.Record({
    'username' : IDL.Text,
    'role' : Role,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDonationRecord' : IDL.Func([DonorId, DonationEntry], [], []),
    'addGroceryItem' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateSubAccount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Role)],
        ['query'],
      ),
    'bulkImport' : IDL.Func([IDL.Text], [ImportResult], []),
    'createDonor' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          DonationType,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [DonorId],
        [],
      ),
    'createSubAccount' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
    'deleteDonor' : IDL.Func([DonorId], [], []),
    'deleteGroceryItem' : IDL.Func([IDL.Text], [], []),
    'deleteSubAccount' : IDL.Func([IDL.Text], [], []),
    'editDonor' : IDL.Func(
        [
          DonorId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          DonationType,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationsByDateRange' : IDL.Func(
        [DonorId, Time, Time],
        [IDL.Vec(DonationEntry)],
        ['query'],
      ),
    'getDonationsForDonor' : IDL.Func(
        [DonorId],
        [IDL.Vec(DonationEntry)],
        ['query'],
      ),
    'getDonor' : IDL.Func([DonorId], [IDL.Opt(Donor)], ['query']),
    'getDonorsByPlace' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
    'getGroceryItems' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRoleTypes' : IDL.Func([], [IDL.Vec(Role)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubAccounts' : IDL.Func([], [IDL.Vec(SubAccount)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };