/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DonationEntry {
  'donationType' : DonationType,
  'submittedBy' : string,
  'notes' : string,
  'timestamp' : Time,
}
export type DonationType = { 'money' : number } |
  { 'groceries' : Array<GroceryItem> };
export interface Donor {
  'initialDonationType' : DonationType,
  'mapLink' : [] | [string],
  'name' : string,
  'logNumber' : DonorId,
  'addressNumber' : string,
  'address' : string,
  'notes' : string,
  'addedDate' : Time,
  'place' : string,
  'donations' : Array<DonationEntry>,
}
export type DonorId = number;
export interface GroceryItem { 'name' : string, 'quantity' : [] | [string] }
export interface ImportResult {
  'errors' : Array<[bigint, string]>,
  'totalRows' : bigint,
  'importedCount' : bigint,
}
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface SubAccount {
  'username' : string,
  'role' : Role,
  'passwordHash' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDonationRecord' : ActorMethod<[DonorId, DonationEntry], undefined>,
  'addGroceryItem' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateSubAccount' : ActorMethod<[string, string], [] | [Role]>,
  'bulkImport' : ActorMethod<[string], ImportResult>,
  'createDonor' : ActorMethod<
    [string, string, string, string, DonationType, string, [] | [string]],
    DonorId
  >,
  'createSubAccount' : ActorMethod<[string, string, Role], undefined>,
  'deleteDonor' : ActorMethod<[DonorId], undefined>,
  'deleteGroceryItem' : ActorMethod<[string], undefined>,
  'deleteSubAccount' : ActorMethod<[string], undefined>,
  'editDonor' : ActorMethod<
    [
      DonorId,
      string,
      string,
      string,
      string,
      DonationType,
      string,
      [] | [string],
    ],
    undefined
  >,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationsByDateRange' : ActorMethod<
    [DonorId, Time, Time],
    Array<DonationEntry>
  >,
  'getDonationsForDonor' : ActorMethod<[DonorId], Array<DonationEntry>>,
  'getDonor' : ActorMethod<[DonorId], [] | [Donor]>,
  'getDonorsByPlace' : ActorMethod<[string], Array<Donor>>,
  'getGroceryItems' : ActorMethod<[], Array<string>>,
  'getRoleTypes' : ActorMethod<[], Array<Role>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubAccounts' : ActorMethod<[], Array<SubAccount>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];